export { default as Team } from "./Icons/Team";
export { default as Clock } from "./Icons/Clock";
export { default as Box } from "./Icons/Box";
export { default as Palette } from "./Icons/Palette";
export { default as Phone } from "./Icons/Phone";
export { default as Camera } from "./Icons/Camera";
export { default as X } from "./Icons/X";
export { default as Plus } from "./Icons/Plus";
export { default as ChevronDown } from "./Icons/ChevronDown";
export type { IconProps } from "./types";
