name: Javascript Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Eslint check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true